[2022-08-09 19:55:28,926] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: group_dag.transforms manual__2022-08-09T19:54:16.187881+00:00 [queued]>
[2022-08-09 19:55:28,932] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: group_dag.transforms manual__2022-08-09T19:54:16.187881+00:00 [queued]>
[2022-08-09 19:55:28,932] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-08-09 19:55:28,933] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-08-09 19:55:28,934] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-08-09 19:55:28,941] {taskinstance.py:1377} INFO - Executing <Task(SubDagOperator): transforms> on 2022-08-09 19:54:16.187881+00:00
[2022-08-09 19:55:28,945] {standard_task_runner.py:52} INFO - Started process 11694 to run task
[2022-08-09 19:55:28,947] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'group_dag', 'transforms', 'manual__2022-08-09T19:54:16.187881+00:00', '--job-id', '87', '--raw', '--subdir', 'DAGS_FOLDER/group_dag.py', '--cfg-path', '/tmp/tmp1w5p1iqt', '--error-file', '/tmp/tmpr3uim8tx']
[2022-08-09 19:55:28,948] {standard_task_runner.py:80} INFO - Job 87: Subtask transforms
[2022-08-09 19:55:28,982] {task_command.py:369} INFO - Running <TaskInstance: group_dag.transforms manual__2022-08-09T19:54:16.187881+00:00 [running]> on host 40fffbcee5cb
[2022-08-09 19:55:29,019] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=group_dag
AIRFLOW_CTX_TASK_ID=transforms
AIRFLOW_CTX_EXECUTION_DATE=2022-08-09T19:54:16.187881+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-09T19:54:16.187881+00:00
[2022-08-09 19:55:29,020] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:202: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-08-09 19:55:29,037] {subdag.py:176} INFO - Created DagRun: scheduled__2022-08-09T19:54:16.187881+00:00
[2022-08-10 03:38:18,293] {taskinstance.py:1153} INFO - Dependencies not met for <TaskInstance: group_dag.transforms manual__2022-08-09T19:54:16.187881+00:00 [running]>, dependency 'Task Instance State' FAILED: Task is in the 'running' state.
[2022-08-10 03:38:18,295] {taskinstance.py:1153} INFO - Dependencies not met for <TaskInstance: group_dag.transforms manual__2022-08-09T19:54:16.187881+00:00 [running]>, dependency 'Task Instance Not Running' FAILED: Task is in the running state
[2022-08-10 03:38:18,298] {local_task_job.py:101} INFO - Task is not able to be run
[2022-08-10 06:58:13,809] {local_task_job.py:221} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2022-08-10 06:58:13,813] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 11694. PIDs of all processes in the group: [11694]
[2022-08-10 06:58:13,814] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 11694
[2022-08-10 06:58:13,815] {taskinstance.py:1541} ERROR - Received SIGTERM. Terminating subprocesses.
[2022-08-10 06:58:13,912] {process_utils.py:75} INFO - Process psutil.Process(pid=11694, status='terminated', exitcode=0, started='19:55:28') (11694) terminated with exit code 0
